name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Install compiler
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev libgit2-dev
    
    - name: Compile code
      run: make
